In [22]:
import numpy as np
import pandas as pd

In [23]:
tweets_df = pd.read_csv('tweet_and_emotion.csv')

In [24]:
tweets_df.head()

tweet emotions
0  @ZubairSabirPTI  pls dont insult the word 'Molna'    anger
1  @ArcticFantasy I would have almost took offens...    anger
2  @IllinoisLoyalty that Rutgers game was an abom...    anger
3  @CozanGaming that's what lisa asked before she...    anger
4  Sometimes I get mad over something so minuscul...    anger

In [25]:
tweets_df['emotions'].unique()

array(['anger', 'fear', 'joy', 'sadness', 'neutral'], dtype=object)

In [26]:
from nltk.corpus import stopwords
import string
from nltk import word_tokenize
from nltk.stem import PorterStemmer
import re

In [27]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [28]:
porter = PorterStemmer()
stopwords= stopwords.words('english')

In [38]:
def cleaning (text):
    # this code will remove the punctuation from the text
    text= ''.join([word.lower() for word in text if word not in string.punctuation])
    # this code will remove URL from the text
    text = re.sub(r'http\S+', '', text)

    # tokenization with nltk
    text = word_tokenize(text)

    # stemming with nltk and removing stop words
    text = [porter.stem(word) for word in text if word not in stop_words]
    return text

In [39]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [41]:
tfidf_vect = TfidfVectorizer()

In [42]:
tfidf_vect.fit(tweets_df['tweet'])
X = tfidf_vect.transform(tweets_df['tweet'])
y = tweets_df['emotions']

In [43]:
X_tfidf_df = pd.DataFrame(X.toarray())
X_tfidf_df.columns = tfidf_vect.get_feature_names_out()

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [45]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel='linear', C=1.0, gamma='auto')
svm_classifier.fit(X_train, y_train)

SVC(gamma='auto', kernel='linear')

In [46]:
y_pred = svm_classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score
confusion_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test,y_pred, target_names = tweets_df['emotions'].unique())
print("OVERALL")
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Precision:', precision_score(y_test, y_pred, average='weighted'))
print('Recall:', recall_score(y_test, y_pred, average='weighted'))
print('F1 score:', f1_score(y_test, y_pred, average='weighted'))
print(report)
print(confusion_matrix)

OVERALL
Accuracy: 0.7256470588235294
Precision: 0.7527017273330525
Recall: 0.7256470588235294
F1 score: 0.7305242855791627
              precision    recall  f1-score   support

       anger       0.88      0.68      0.77       380
        fear       0.81      0.82      0.82       423
         joy       0.82      0.70      0.75       436
     sadness       0.53      0.79      0.64       418
     neutral       0.73      0.64      0.68       468

    accuracy                           0.73      2125
   macro avg       0.75      0.73      0.73      2125
weighted avg       0.75      0.73      0.73      2125

[[260  15  10  56  39]
 [  8 347   3  41  24]
 [  6  15 305  98  12]
 [  6  15  33 330  34]
 [ 17  34  22  95 300]]
